x-net-base: &net-base
  networks:
    - dcbanknet
x-health-base: &health-base
  healthcheck:
    interval: 10s
    retries: 11
    start_period: 10s
    timeout: 5m
services:
  accounts:
    <<: *net-base
    image: "thedeno/accounts:latest"
    container_name: accounts-ms
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_R2DBC_URL: "r2dbc:postgresql://accounts-postgres:5432/accounts_db"
      SPRING_FLYWAY_URL: "jdbc:postgresql://accounts-postgres:5432/accounts_db"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver-ms"
    ports:
      - "3000:80"
    depends_on:
      accounts-postgres:
        condition: service_healthy
      configserver:
        condition: service_healthy
  accounts-postgres:
    <<: [*net-base, *health-base]
    image: "postgres:17-alpine"
    container_name: accounts-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "accounts_db"
    ports:
      - "35432:5432"
    healthcheck:
      test: "pg_isready -d accounts_db"
  cards:
    <<: *net-base
    image: "thedeno/cards:latest"
    container_name: cards-ms
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_R2DBC_URL: "r2dbc:postgresql://cards-postgres:5432/cards_db"
      SPRING_FLYWAY_URL: "jdbc:postgresql://cards-postgres:5432/cards_db"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver-ms"
    ports:
      - "4000:80"
    depends_on:
      cards-postgres:
        condition: service_healthy
      configserver:
        condition: service_healthy
  cards-postgres:
    <<: [*net-base, *health-base]
    image: "postgres:17-alpine"
    container_name: cards-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cards_db"
    healthcheck:
      test: "pg_isready -d cards_db"
  configserver:
    <<: [*net-base, *health-base]
    image: "thedeno/configserver:latest"
    container_name: configserver-ms
    ports:
      - "5000:80"
    healthcheck:
      test: "curl --fail --silent localhost/actuator/health/readiness | grep UP || exit 1"
networks:
  dcbanknet:
    driver: bridge
